### ISSUE TITLE
Improve icon scaling algorithm to scale down more often

### ISSUE THREAD

**Issue by gryf** [roblillack/wmaker#8]
Hi!

I was tried to reach you via email and a comment under #5 PR, but failed to grab your attention. I just have a question really, not the issue. Do you have any objections to pull this change into upstream wmaker by me, or by yourself?

**Comment by roblillack** [comment]
Hi @gryf. 👋 Sorry it took me so long … I just submitted a patch to the mailing list. Thanks for pushing me!
